from ..models import ResponseModel
from ._api import MikuChatApi

class Email(MikuChatApi):
    """邮件"""
    def __init__(self, **kwargs): super().__init__(**kwargs)
    """桐乃"""
    async def Kirino(self, qq: int, title: str, body: str, *, method: str = "POST"): ...
    """纨素"""
    async def Shiruku(self, qq: int, title: str, body: str, *, method: str = "POST"): ...

    @property
    def raw_data(self) -> dict: ...
    @property
    def raw_code(self) -> int: ...
    @property
    def error(self) -> bool: ...
    @property
    def model(self) -> "ResponseModel": ...