from ..models import ResponseModel
from ._api import MikuChatApi

class Prize(MikuChatApi):
    """抽奖"""
    def __init__(self, **kwargs): ...
    """投入通用货币"""
    async def insert_coins(self, qq: int, quantity: int): ...
    """获取奖池内所有通用货币"""
    async def get_prize_coin(self): ...
    """获取奖池内投入通用货币多少的用户排行榜"""
    async def get_prize_coin_rank(self, quantity: int): ...

    @property
    def data(self) -> dict: ...
    @property
    def raw_code(self) -> int: ...
    @property
    def error(self) -> bool: ...
    @property
    def model(self) -> "ResponseModel": ...