from ._api import Yuuz12Api
from ..models import ResponseModel

class Statistics(Yuuz12Api):
    """统计数据"""
    def __init__(self, **kwargs): ...
    """调用统计"""
    async def update_statistics(self, group_id: int, type: str): ...

    @property
    def data(self) -> dict: ...
    @property
    def raw_code(self) -> int: ...
    @property
    def error(self) -> bool: ...
    @property
    def model(self) -> "ResponseModel": ...